# Zero-Knowledge Proof System Configuration

# ZK System Mode
zk_mode: production  # Options: development, staging, production

# Circuit Parameters
circuit:
  max_constraints: 1000000
  optimization_level: 2
  debug_mode: false
  enabled_circuits:
    - sgd
    - lora
    - aggregated

# Proof Generation
prover:
  num_workers: -1  # Use all CPU cores
  batch_size: 32
  timeout_ms: 30000
  max_retries: 3
  retry_delay_ms: 1000
  memory_limit_mb: 2048

# LoRA Configuration
lora:
  max_rank: 128
  default_rank: 16
  default_alpha: 32.0
  optimized_ranks: [4, 8, 16, 32, 64]
  min_compression_ratio: 10.0

# Proof Verification
verifier:
  batch_verification: true
  max_batch_size: 64
  timeout_ms: 5000
  cache_verified: true

# Caching
cache:
  enabled: true
  memory_cache_size_mb: 500
  disk_cache_size_gb: 10
  cache_dir: ~/.pot/zk_cache
  ttl_seconds: 3600
  warm_cache: true

# Monitoring
monitoring:
  enabled: true
  collection_interval: 60
  export_to_file: true
  metrics_file: experimental_results/zk_metrics.json
  regression_detection:
    enabled: true
    baseline_window: 100
    threshold_percent: 20

# Fallback Behavior
fallback:
  enabled: true
  triggers:
    - binary_not_found
    - proof_timeout
    - memory_exceeded
    - repeated_failures
  failure_threshold: 3
  log_fallbacks: true

# Security Settings
security:
  field_size: 255
  soundness_error: 128
  hash_function: poseidon
  commitment_scheme: ipa
  extra_checks: true

# Environment Overrides
environments:
  development:
    circuit:
      max_constraints: 10000
      debug_mode: true
    prover:
      num_workers: 2
      batch_size: 4
  production:
    circuit:
      max_constraints: 1000000
      optimization_level: 3
    prover:
      num_workers: -1
      batch_size: 32

# Performance Targets
performance_targets:
  sgd_proof_target_ms: 500
  lora_proof_target_ms: 100
  verification_target_ms: 10
  alert_on_miss: true
